#!/usr/bin/env python3
"""directed_ring.py -- the paper's sharpest falsifiable claim, tested directly.

Lemma 2 + Theorem 4 (arXiv:2609.25226, SM S3).  Take the Jacobian

    J(b) = [[0, I], [-L, -B]]

with L the NON-HERMITIAN circulant Laplacian of a directed first-neighbour ring,
generated by the first column

    c = [1, -delta, 0, ..., 0, -(1-delta)],   0 <= delta <= 1,  delta != 1/2

so each node is pulled by its clockwise neighbour with weight delta and its
counter-clockwise neighbour with weight 1-delta.  delta = 1/2 is the undirected
ring and the theorem explicitly excludes it.

CLAIM: for every delta != 1/2, the best HOMOGENEOUS damping b*_hom 1_N is not
even a local optimum -- there is always a heterogeneous perturbation that
lowers Lambda_max.  Proposition 5 says the opposite happens on undirected
networks, where Lambda_max is non-differentiable at b*_hom, so the kink can hold.

So this file runs both, and the CONTRAST is the test.  A rebuild that only ran
the undirected case would find nothing and conclude the paper was wrong; the
paper predicted that null.

Everything here calls stability.py, which `--selftest` has already checked
against the exact closed form Lambda_max = -sqrt(mu_2) at b = 2 sqrt(mu_2).
"""
from __future__ import annotations

import argparse

import numpy as np

from stability import J_second, lam_max


def circulant(c):
    """Circulant with c as the FIRST COLUMN, matching the paper's convention."""
    N = len(c)
    return np.array([[c[(i - j) % N] for j in range(N)] for i in range(N)])


def L_directed_ring(N, delta):
    c = np.zeros(N)
    c[0] = 1.0
    c[1] = -delta
    c[-1] = -(1.0 - delta)
    return circulant(c)


def J_of(b, L):
    n = len(b)
    return np.block([[np.zeros((n, n)), np.eye(n)], [-L, -np.diag(b)]])


def best_homogeneous_L(L, lo=1e-3, hi=8.0, n=40001):
    N = L.shape[0]
    bs = np.linspace(lo, hi, n)
    v = [lam_max(J_of(np.full(N, b), L)) for b in bs]
    i = int(np.argmin(v))
    # one golden refinement around the grid minimum so the baseline is not
    # limited by the scan step -- the baseline must be the STRONG side
    a, c = bs[max(0, i - 1)], bs[min(n - 1, i + 1)]
    for _ in range(200):
        m1, m2 = a + (c - a) / 3, c - (c - a) / 3
        if lam_max(J_of(np.full(N, m1), L)) < lam_max(J_of(np.full(N, m2), L)):
            c = m2
        else:
            a = m1
    b = (a + c) / 2
    return float(b), lam_max(J_of(np.full(N, b), L))


def best_perturbation(L, bhom, eps):
    """Theorem 4's own descent direction: v = e_alpha - e_beta.  The proof shows
    the Hessian has H_{alpha beta} > max(H_aa, H_bb) for some pair, so a
    difference of two coordinates descends.  Scan pairs at fixed step eps."""
    N = L.shape[0]
    base = lam_max(J_of(np.full(N, bhom), L))
    best = (base, None)
    for a in range(N):
        for bb in range(N):
            if a == bb:
                continue
            v = np.zeros(N)
            v[a], v[bb] = 1.0, -1.0
            val = lam_max(J_of(np.full(N, bhom) + eps * v, L))
            if val < best[0]:
                best = (val, (a, bb))
    return base, best[0], best[1]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--N", type=int, default=6)
    ap.add_argument("--eps", type=float, default=0.05)
    a = ap.parse_args()
    N = a.N

    print(f"directed ring, N = {N}, perturbation e_a - e_b at eps = {a.eps}")
    print("delta = 1/2 is the UNDIRECTED ring; the theorem excludes it.\n")
    print(f"{'delta':>6} {'Hermitian?':>11} {'b*_hom':>9} {'Lmax(hom)':>11} "
          f"{'Lmax(pert)':>11} {'gain':>10}  pair")
    for delta in [0.0, 0.1, 0.2, 0.3, 0.4, 0.45, 0.49, 0.5, 0.51, 0.55, 0.6, 0.8, 1.0]:
        L = L_directed_ring(N, delta)
        herm = "yes" if np.allclose(L, L.T) else "no"
        bh, Lh = best_homogeneous_L(L)
        base, bestv, pair = best_perturbation(L, bh, a.eps)
        gain = base - bestv
        tag = f"{pair}" if pair else "-- none --"
        print(f"{delta:6.2f} {herm:>11} {bh:9.5f} {Lh:11.6f} {bestv:11.6f} "
              f"{gain:10.2e}  {tag}")

    print("\nsame, with eps -> 0 on the most directed case (delta = 0):")
    L = L_directed_ring(N, 0.0)
    bh, Lh = best_homogeneous_L(L)
    print(f"  b*_hom = {bh:.6f}   Lambda_max = {Lh:.8f}")
    print(f"  {'eps':>8} {'best Lmax':>14} {'gain':>12} {'gain/eps^2':>12}")
    for eps in (0.2, 0.1, 0.05, 0.02, 0.01, 0.005):
        base, bestv, pair = best_perturbation(L, bh, eps)
        g = base - bestv
        print(f"  {eps:8.4f} {bestv:14.8f} {g:12.3e} {g/eps**2:12.4f}")
    print("  a gain that scales as eps^2 is the negative Hessian eigenvalue of")
    print("  Theorem 4 showing itself; a gain that scales as eps would be a kink.")


if __name__ == "__main__":
    main()
